# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
hosts = {
  "host0" => "192.168.33.10",
  "host1" => "192.168.33.11",
  "host2" => "192.168.33.12"
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  hosts.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.box = "ubuntu/bionic64"
      machine.vm.hostname = "%s" % name
      machine.vm.network :private_network, ip: ip
      machine.vm.provider "virtualbox" do |v|
          v.name = name
          v.customize ["modifyvm", :id, "--memory", 256]
      end
    end
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.forward_agent = true
  config.vm.synced_folder Dir.getwd, "/home/vagrant/roles/ansible-zookeeper", nfs: true

    config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
  end


  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = true
  end

  # debian
  config.vm.define 'ubuntu', primary: true do |c|
    c.vm.network "private_network", ip: "192.168.100.2"
    c.vm.box = "trusty-server-cloudimg-amd64-vagrant-disk1"
  	c.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  	c.vm.provision "shell" do |s|
		  s.inline = "apt-get update -y; apt-get install ansible -y;"
		  s.privileged = true
    end
  end

  # centos:
  config.vm.define 'centos' do |c|
  	c.vm.network "private_network", ip: "192.168.100.3"
    c.vm.box = "centos65-x86_64-20140116"
  	c.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
  	c.vm.provision "shell" do |s|
      s.inline = "yum install -y nc java-1.7.0-openjdk-devel ansible"
		  s.privileged = true
	  end
  end

  # centos 7
  config.vm.define 'centos7' do |c|
  	c.vm.network "private_network", ip: "192.168.100.4"
    c.vm.box = "centos/7"
  	c.vm.provision "shell" do |s|
      s.inline = "yum install -y epel-release; yum install -y nc java-1.7.0-openjdk-devel ansible"
		  s.privileged = true
	  end
  end

    # Virtualbox provider information
  config.vm.provider :virtualbox do |vb|
    vb.name = "postgresql"
    vb.memory = 512
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]

    database_vdi = "#{Dir.home}/.database.vdi"

    unless File.exist?(database_vdi)
      vb.customize ['createhd', '--filename', database_vdi, '--size', 20 * 1024]
    end
    vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', database_vdi]

  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "setup.yml"
    ansible.inventory_path = "inventory"
    ansible.limit = "db"
    # Having trouble? Uncomment below to troubleshoot.
    # ansible.verbose = "vvvv"
  end
end